version: "3.9"
services: 
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        image: ghcr.io/markhuang1212/cdgr-backend
        ports: 
            - "8080:8080"
            - "8443:8443"
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
        deploy:
            resources:
                limits:
                    memory: 4G
                    cpus: '2.0'
            restart_policy:
                condition: on-failure
                max_attempts: 3
    runtime-compile:
        build: 
            context: .
            dockerfile: runtime-compile/Dockerfile
        image: ghcr.io/markhuang1212/cdgr-compile
        entrypoint: ["/usr/bin/true"]
    runtime-exec:
        build: 
            context: .
            dockerfile: runtime-exec/Dockerfile
        image: ghcr.io/markhuang1212/cdgr-exec
        entrypoint: ["/usr/bin/true"]
    db:
        image: redis
