name: Pull Request Check
on:
  pull_request_review:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
        env:
          FROM_SOURCE: true
